import gzip
import json
from typing import List, Optional, Tuple

from cortex_xdr_client.api.authentication import Authentication
from cortex_xdr_client.api.base_api import BaseAPI
from cortex_xdr_client.api.version import APIVersion
from cortex_xdr_client.api.models.exceptions import InvalidResponseException, UnsuccessfulQueryStatusException
from cortex_xdr_client.api.models.filters import new_request_data


class XQLAPI(BaseAPI):
    def __init__(self, auth: Authentication, fqdn: str, timeout: Tuple[int, int],
                 api_version: APIVersion = APIVersion.V3) -> None:
        super(XQLAPI, self).__init__(auth, fqdn, "xql", timeout, api_version)

    def _get_start_xql_filter(self, query: str, time_period: int = None, from_date: int = None,
                              to_date: int = None, tenants: List[str] = None, params: dict = None) -> dict:
        filter = {"query": query}
        timeframe = {}
        if tenants is not None and len(tenants) > 0:
            filter["tenants"] = tenants
        if from_date is not None and to_date is not None:
            timeframe = {"from": from_date, "to": to_date}
        elif time_period is not None:
            timeframe = {"relativeTime": time_period}
        filter["timeframe"] = timeframe
        return self.extend(filter, params or {})

    def _get_xql_results_filter(self, query_id: str, limit: int = None, params: dict = None) -> dict:
        filter = {"query_id": query_id}
        if limit is not None:
            filter["limit"] = limit
        return self.extend(filter, params or {})

    # https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-api/cortex-xdr-apis/xql-apis/start-xql-query.html
    def start_xql_query(self, query: str, time_period: int = None, from_date: int = None,
                        to_date: int = None, tenants: List[str] = None, params: dict = None) -> Optional[str]:
        """
        Starts an XQL Query.
        :param query: String of the XQL query.
        :param time_period: Relative Unix timestamp representing the last X hours.
        :param from_date: Absolute Unix timestamp representing a date
        :param to_date: Absolute Unix timestamp representing a date
        :param tenants: List of strings used for running APIs on local and Managed Security tenants.
        :param params: Dictionary of parameters to be passed to the request data
        :return: String representing the unique ID generate by the response to Start XQL Query API.
        """
        """Starts an XQL Query and returns the ID of the query. """
        filters = self._get_start_xql_filter(query, time_period, from_date, to_date, tenants, params)
        request_data = new_request_data(other=filters)
        response = self._call(call_name="start_xql_query", json_value=request_data)
        resp_json = response.json()
        if "reply" not in resp_json:
            raise InvalidResponseException(response, ["reply"])
        return resp_json["reply"]

    # https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-api/cortex-xdr-apis/xql-apis/get-xql-query-results.html
    def get_query_results(self, query_id: str, limit: int = None, params: dict = None) -> Optional[dict]:
        """
        Returns the results of an XQL Query.
        :param query_id: teger representing the unique execution ID generated by the response to Start an XQL Query API
        :param limit: Maximum number of results; values over 1000 may return a stream.
        :param params: Dictionary of parameters to be passed to the request data
        :return: Dictionary of results
        """
        filters = self._get_xql_results_filter(query_id, limit, params)
        request_data = new_request_data(other=filters)
        response = self._call(call_name="get_query_results", json_value=request_data)
        resp_json = response.json()
        if "reply" not in resp_json:
            raise InvalidResponseException(response, ["reply"])

        reply = resp_json["reply"]
        if "status" not in reply:
            raise InvalidResponseException(response, ["status"])

        if "SUCCESS" != reply["status"]:
            raise UnsuccessfulQueryStatusException(reply["status"])

        if "results" not in reply:
            raise InvalidResponseException(response, ["results"])
        results = reply["results"]
        if isinstance(results, dict) and results.get("stream_id") is not None:
            return self.get_query_results_stream(results["stream_id"])
        return results

    # https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-api/cortex-xdr-apis/xql-apis/get-xql-query-exported-data.html
    def get_query_results_stream(self, stream_id: str) -> Optional[dict]:
        """
        Returns the results of an XQL Query.
        :param stream_id: Integer representing the unique ID generate by the response to Get XQL Query Results API.
        :return:  Dictionary of results
        """
        request_data = {
            "request_data": {
                "stream_id":          stream_id,
                "is_gzip_compressed": True,
            }
        }
        response = self._call(call_name="get_query_results_stream", json_value=request_data,
                              header_params={"Accept-Encoding": "gzip"})
        content = response.content
        # requests may already have decoded Content-Encoding: gzip.
        if content.startswith(b"\x1f\x8b"):
            content = gzip.decompress(content)
        data = content.decode("utf-8")
        logs = [json.loads(line) for line in data.splitlines() if line.strip() != ""]
        return {"data": logs}
