from typing import Any, List, Optional, Tuple, Union

from cortex_xdr_client.api.operation import UNSET, UnsetType

import gzip
import json

from cortex_xdr_client.api.authentication import Authentication
from cortex_xdr_client.api.base_api import BaseAPI
from cortex_xdr_client.api.version import APIVersion
from cortex_xdr_client.api.models.exceptions import InvalidResponseException, UnsuccessfulQueryStatusException
from cortex_xdr_client.api.models.filters import new_request_data


class XQLAPI(BaseAPI):
    def __init__(self, auth: Authentication, fqdn: str, timeout: Tuple[int, int],
                 api_version: APIVersion = APIVersion.V3) -> None:
        super(XQLAPI, self).__init__(auth, fqdn, "xql", timeout, api_version)

    def _get_start_xql_filter(self, query: str, time_period: int = None, from_date: int = None,
                              to_date: int = None, tenants: List[str] = None, params: dict = None) -> dict:
        filter = {"query": query}
        timeframe = {}
        if tenants is not None and len(tenants) > 0:
            filter["tenants"] = tenants
        if from_date is not None and to_date is not None:
            timeframe = {"from": from_date, "to": to_date}
        elif time_period is not None:
            timeframe = {"relativeTime": time_period}
        filter["timeframe"] = timeframe
        return self.extend(filter, params or {})

    def _get_xql_results_filter(self, query_id: str, limit: int = None, params: dict = None) -> dict:
        filter = {"query_id": query_id}
        if limit is not None:
            filter["limit"] = limit
        return self.extend(filter, params or {})

    # https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-api/cortex-xdr-apis/xql-apis/start-xql-query.html
    def start_xql_query(self, query: str, time_period: int = None, from_date: int = None,
                        to_date: int = None, tenants: List[str] = None, params: dict = None) -> Optional[str]:
        """
        Starts an XQL Query.
        :param query: String of the XQL query.
        :param time_period: Relative Unix timestamp representing the last X hours.
        :param from_date: Absolute Unix timestamp representing a date
        :param to_date: Absolute Unix timestamp representing a date
        :param tenants: List of strings used for running APIs on local and Managed Security tenants.
        :param params: Dictionary of parameters to be passed to the request data
        :return: String representing the unique ID generate by the response to Start XQL Query API.
        """
        """Starts an XQL Query and returns the ID of the query. """
        filters = self._get_start_xql_filter(query, time_period, from_date, to_date, tenants, params)
        request_data = new_request_data(other=filters)
        response = self._call(call_name="start_xql_query", json_value=request_data)
        resp_json = response.json()
        if "reply" not in resp_json:
            raise InvalidResponseException(response, ["reply"])
        return resp_json["reply"]

    # https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-api/cortex-xdr-apis/xql-apis/get-xql-query-results.html
    def get_query_results(self, query_id: str, limit: int = None, params: dict = None) -> Optional[dict]:
        """
        Returns the results of an XQL Query.
        :param query_id: teger representing the unique execution ID generated by the response to Start an XQL Query API
        :param limit: Maximum number of results; values over 1000 may return a stream.
        :param params: Dictionary of parameters to be passed to the request data
        :return: Dictionary of results
        """
        filters = self._get_xql_results_filter(query_id, limit, params)
        request_data = new_request_data(other=filters)
        response = self._call(call_name="get_query_results", json_value=request_data)
        resp_json = response.json()
        if "reply" not in resp_json:
            raise InvalidResponseException(response, ["reply"])

        reply = resp_json["reply"]
        if "status" not in reply:
            raise InvalidResponseException(response, ["status"])

        if "SUCCESS" != reply["status"]:
            raise UnsuccessfulQueryStatusException(reply["status"])

        if "results" not in reply:
            raise InvalidResponseException(response, ["results"])
        results = reply["results"]
        if isinstance(results, dict) and results.get("stream_id") is not None:
            return self.get_query_results_stream(results["stream_id"])
        return results

    # https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-api/cortex-xdr-apis/xql-apis/get-xql-query-exported-data.html
    def get_query_results_stream(self, stream_id: str) -> Optional[dict]:
        """
        Returns the results of an XQL Query.
        :param stream_id: Integer representing the unique ID generate by the response to Get XQL Query Results API.
        :return:  Dictionary of results
        """
        request_data = {
            "request_data": {
                "stream_id":          stream_id,
                "is_gzip_compressed": True,
            }
        }
        response = self._call(call_name="get_query_results_stream", json_value=request_data,
                              header_params={"Accept-Encoding": "gzip"})
        content = response.content
        # requests may already have decoded Content-Encoding: gzip.
        if content.startswith(b"\x1f\x8b"):
            content = gzip.decompress(content)
        data = content.decode("utf-8")
        logs = [json.loads(line) for line in data.splitlines() if line.strip() != ""]
        return {"data": logs}


    def start_xql_query_request(self, *,
                                accept_encoding: Union[str, None, UnsetType] = UNSET,
                                query: Union[str, None, UnsetType] = UNSET,
                                tenants: Union[List[str], None, UnsetType] = UNSET,
                                timeframe: Union[dict, None, UnsetType] = UNSET) -> Any:
        """Start an XQL Query

        POST /public_api/v1/xql/start_xql_query
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param query: body field query.
        :param tenants: body field tenants.
        :param timeframe: body field timeframe.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = self._values({'query': query, 'tenants': tenants, 'timeframe': timeframe})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/start_xql_query', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = self._values({'query': query, 'tenants': tenants, 'timeframe': timeframe})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/start_xql_query', method='post',
                body=body,
            )

    def get_query_results_request(self, *,
                                  accept_encoding: Union[str, None, UnsetType] = UNSET,
                                  query_id: Union[str, None, UnsetType] = UNSET,
                                  pending_flag: Union[bool, None, UnsetType] = UNSET,
                                  limit: Union[int, None, UnsetType] = UNSET,
                                  format: Union[Any, None, UnsetType] = UNSET) -> Any:
        """Get XQL Query Results

        POST /public_api/v1/xql/get_query_results
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param query_id: body field query_id.
        :param pending_flag: body field pending_flag.
        :param limit: body field limit.
        :param format: body field format.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = self._values({'query_id': query_id, 'pending_flag': pending_flag, 'limit': limit, 'format': format})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/get_query_results', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = self._values({'query_id': query_id, 'pending_flag': pending_flag, 'limit': limit, 'format': format})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/get_query_results', method='post',
                body=body,
            )

    def get_quota(self, *,
                  accept_encoding: Union[str, None, UnsetType] = UNSET,
                  body: Union[dict, None, UnsetType] = UNSET) -> Any:
        """Get XQL Query Quota

        POST /public_api/v1/xql/get_quota
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param body: payload field body.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = body
            return self._operation(
                '/public_api/v1/xql/get_quota', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = body
            return self._operation(
                '/public_api/v1/xql/get_quota', method='post',
                body=body,
            )

    def get_query_results_stream_request(self, *,
                                         accept_encoding: Union[str, None, UnsetType] = UNSET,
                                         accept_encoding_gzip: Union[str, None, UnsetType] = UNSET,
                                         stream_id: Union[str, None, UnsetType] = UNSET,
                                         is_gzip_compressed: Union[bool, None, UnsetType] = UNSET) -> Any:
        """Get XQL Query Results Stream

        POST /public_api/v1/xql/get_query_results_stream
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param accept_encoding_gzip: Compatibility alias for the v3 Accept-Encoding header; pass 'gzip'.
        :param stream_id: body field stream_id.
        :param is_gzip_compressed: body field is_gzip_compressed.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            if accept_encoding is not UNSET and accept_encoding_gzip is not UNSET:
                raise ValueError('Specify one Accept-Encoding value')
            encoding = accept_encoding_gzip if accept_encoding_gzip is not UNSET else accept_encoding
            body = self._values({'stream_id': stream_id, 'is_gzip_compressed': is_gzip_compressed})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/get_query_results_stream', method='post',
                headers={'Accept-Encoding': encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding_gzip=accept_encoding_gzip)
            body = self._values({'stream_id': stream_id, 'is_gzip_compressed': is_gzip_compressed})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/get_query_results_stream', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )

    def add_dataset(self, *,
                    accept_encoding: Union[str, None, UnsetType] = UNSET,
                    dataset_name: Union[str, None, UnsetType] = UNSET,
                    dataset_type: Union[Any, None, UnsetType] = UNSET,
                    dataset_schema: Union[dict, None, UnsetType] = UNSET) -> Any:
        """Add Dataset

        POST /public_api/v1/xql/add_dataset
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param dataset_name: body field dataset_name.
        :param dataset_type: body field dataset_type.
        :param dataset_schema: body field dataset_schema.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = self._values({'dataset_name': dataset_name, 'dataset_type': dataset_type, 'dataset_schema': dataset_schema})
            body = self._values({'request': body, **{}})
            return self._operation(
                '/public_api/v1/xql/add_dataset', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = self._values({'dataset_name': dataset_name, 'dataset_type': dataset_type, 'dataset_schema': dataset_schema})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/add_dataset', method='post',
                body=body,
            )

    def delete_dataset(self, *,
                       accept_encoding: Union[str, None, UnsetType] = UNSET,
                       dataset_name: Union[str, None, UnsetType] = UNSET,
                       force: Union[bool, None, UnsetType] = UNSET) -> Any:
        """Delete a dataset

        POST /public_api/v2/xql/delete_dataset
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param dataset_name: body field dataset_name.
        :param force: body field force.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = self._values({'dataset_name': dataset_name, 'force': force})
            body = self._values({'request': body, **{}})
            return self._operation(
                '/public_api/v2/xql/delete_dataset', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = self._values({'dataset_name': dataset_name, 'force': force})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v2/xql/delete_dataset', method='post',
                body=body,
            )

    def get_datasets(self, *,
                     accept_encoding: Union[str, None, UnsetType] = UNSET,
                     request: Union[dict, None, UnsetType] = UNSET,
                     request_data: Union[dict, None, UnsetType] = UNSET) -> Any:
        """Get all datasets

        POST /public_api/v1/xql/get_datasets
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param request: payload field request.
        :param request_data: payload field request_data.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            self._reject_fields(request_data=request_data)
            body = request
            body = self._values({'request': body, **{}})
            return self._operation(
                '/public_api/v1/xql/get_datasets', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding, request=request)
            body = request_data
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/get_datasets', method='post',
                body=body,
            )

    def lookups_add_data(self, *,
                         accept_encoding: Union[str, None, UnsetType] = UNSET,
                         dataset_name: Union[str, None, UnsetType] = UNSET,
                         key_fields: Union[List[str], None, UnsetType] = UNSET,
                         data: Union[dict, None, UnsetType] = UNSET) -> Any:
        """Add or update data in a lookup dataset

        POST /public_api/v1/xql/lookups/add_data
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param dataset_name: body field dataset_name.
        :param key_fields: body field key_fields.
        :param data: body field data.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = self._values({'dataset_name': dataset_name, 'key_fields': key_fields, 'data': data})
            body = self._values({'request': body, **{}})
            return self._operation(
                '/public_api/v1/xql/lookups/add_data', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = self._values({'dataset_name': dataset_name, 'key_fields': key_fields, 'data': data})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/lookups/add_data', method='post',
                body=body,
            )

    def lookups_remove_data(self, *,
                            accept_encoding: Union[str, None, UnsetType] = UNSET,
                            dataset_name: Union[str, None, UnsetType] = UNSET,
                            filters: Union[dict, None, UnsetType] = UNSET) -> Any:
        """Remove data from a lookup dataset

        POST /public_api/v1/xql/lookups/remove_data
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param dataset_name: body field dataset_name.
        :param filters: body field filters.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = self._values({'dataset_name': dataset_name, 'filters': filters})
            body = self._values({'request': body, **{}})
            return self._operation(
                '/public_api/v1/xql/lookups/remove_data', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = self._values({'dataset_name': dataset_name, 'filters': filters})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/lookups/remove_data', method='post',
                body=body,
            )

    def lookups_get_data(self, *,
                         accept_encoding: Union[str, None, UnsetType] = UNSET,
                         dataset_name: Union[str, None, UnsetType] = UNSET,
                         filters: Union[List[dict], None, UnsetType] = UNSET,
                         limit: Union[int, None, UnsetType] = UNSET) -> Any:
        """Get data from a lookup dataset

        POST /public_api/v1/xql/lookups/get_data
        Available in Cortex XDR 3.x, 5.x.
        Returns the complete JSON response, bytes for downloads, or None for an empty response.
        Omit optional fields with UNSET; explicit None is sent as JSON null.
        :param accept_encoding: header field Accept-Encoding.
        :param dataset_name: body field dataset_name.
        :param filters: body field filters.
        :param limit: body field limit.
        """
        self._require_versions((3, 5))
        if self._api_version == APIVersion.V3:
            body = self._values({'dataset_name': dataset_name, 'filters': filters, 'limit': limit})
            body = self._values({'request': body, **{}})
            return self._operation(
                '/public_api/v1/xql/lookups/get_data', method='post',
                headers={'Accept-Encoding': accept_encoding},
                body=body,
            )
        elif self._api_version == APIVersion.V5:
            self._reject_fields(accept_encoding=accept_encoding)
            body = self._values({'dataset_name': dataset_name, 'filters': filters, 'limit': limit})
            body = self._values({'request_data': body, **{}})
            return self._operation(
                '/public_api/v1/xql/lookups/get_data', method='post',
                body=body,
            )
